sudo: required
services:
  - docker

before_install:
  - docker build -t ihorberda/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true ihorberda/react-test npm test

after_success:
  - docker build -t ihorberda/multi-client ./client
  - docker build -t ihorberda/multi-nginx ./nginx
  - docker build -t ihorberda/multi-server ./server
  - docker build -t ihorberda/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push ihorberda/multi-client
  - docker push ihorberda/multi-nginx
  - docker push ihorberda/multi-server
  - docker push ihorberda/multi-worker
